export const mockLostItems = [
    {
        id: 1,
        title: "iPhone 14 Pro",
        description: "Black iPhone 14 Pro with a clear case. Has a small scratch on the back.",
        category: "Electronics",
        location: "Central Park, NYC",
        dateLost: "2024-01-15",
        contactInfo: "john.doe@email.com",
        reward: 100,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUPIfiGgUML8G3ZqsNLHfaCnZK3I5g4tJabQ&s",
        status: "active",
    },
    {
        id: 2,
        title: "Blue Backpack",
        description: "Navy blue Jansport backpack with laptop compartment. Contains important documents.",
        category: "Bags",
        location: "Times Square, NYC",
        dateLost: "2024-01-14",
        contactInfo: "jane.smith@email.com",
        reward: 50,
        image: "/placeholder.svg?height=200&width=300",
        status: "active",
    },
    {
        id: 3,
        title: "Gold Wedding Ring",
        description: 'Gold wedding band with engraving "Forever & Always". Extremely sentimental value.',
        category: "Jewelry",
        location: "Brooklyn Bridge",
        dateLost: "2024-01-13",
        contactInfo: "mike.wilson@email.com",
        reward: 500,
        image: "/placeholder.svg?height=200&width=300",
        status: "active",
    },
    {
        id: 4,
        title: "Black Leather Wallet",
        description: "Black leather wallet with multiple cards and cash. Has a photo of family inside.",
        category: "Documents",
        location: "Grand Central Station",
        dateLost: "2024-01-12",
        contactInfo: "sarah.johnson@email.com",
        reward: 75,
        image: "/placeholder.svg?height=200&width=300",
        status: "claimed",
    },
    {
        id: 5,
        title: "Red Baseball Cap",
        description: "Red New York Yankees baseball cap, slightly worn. Has sentimental value.",
        category: "Clothing",
        location: "Yankee Stadium",
        dateLost: "2024-01-11",
        contactInfo: "tom.brown@email.com",
        reward: 25,
        image: "/placeholder.svg?height=200&width=300",
        status: "active",
    },
    {
        id: 6,
        title: "Car Keys with Remote",
        description: "Honda car keys with black remote and house keys on a blue keychain.",
        category: "Keys",
        location: "Madison Square Garden",
        dateLost: "2024-01-10",
        contactInfo: "lisa.davis@email.com",
        reward: 100,
        image: "/placeholder.svg?height=200&width=300",
        status: "active",
    },
];

export const mockFoundItems = [
    {
        id: 1,
        title: "Silver Watch",
        description: "Silver Casio watch with metal band. Found in good condition.",
        category: "Jewelry",
        location: "Washington Square Park",
        dateFound: "2024-01-16",
        contactInfo: "finder1@email.com",
        image: "/placeholder.svg?height=200&width=300",
        status: "active",
    },
    {
        id: 2,
        title: "Purple Umbrella",
        description: "Purple compact umbrella, appears to be new. Found near subway entrance.",
        category: "Other",
        location: "14th Street Subway",
        dateFound: "2024-01-15",
        contactInfo: "finder2@email.com",
        image: "/placeholder.svg?height=200&width=300",
        status: "active",
    },
    {
        id: 3,
        title: "Student ID Card",
        description: "NYU student ID card for Sarah M. Found near campus.",
        category: "Documents",
        location: "NYU Campus",
        dateFound: "2024-01-14",
        contactInfo: "finder3@email.com",
        image: "/placeholder.svg?height=200&width=300",
        status: "claimed",
    },
    {
        id: 4,
        title: "Wireless Earbuds",
        description: "White Apple AirPods in charging case. Found in coffee shop.",
        category: "Electronics",
        location: "Starbucks on 5th Ave",
        dateFound: "2024-01-13",
        contactInfo: "finder4@email.com",
        image: "/placeholder.svg?height=200&width=300",
        status: "active",
    },
    {
        id: 5,
        title: "Brown Leather Gloves",
        description: "Pair of brown leather gloves, size medium. Found on park bench.",
        category: "Clothing",
        location: "Bryant Park",
        dateFound: "2024-01-12",
        contactInfo: "finder5@email.com",
        image: "/placeholder.svg?height=200&width=300",
        status: "active",
    },
];
  